---
title: "Google data analytics captone project"
author: "akash singh"
date: "2023-03-24"
output: html_document
---

### Introdution

For the capstone project of the Google Data Analytics certificate, I have chosen the Cyclistic bike share data to work on. For the case study, I will perform real-world tasks of a junior data analyst for the marketing team at Cyclistic, a fictional bike-share company in Chicago.
To answer key business questions, I will follow the six steps of the data analysis process : Ask, Prepare, Process, Analyze, Share and Act.


### The scenario

The director of marketing of Cyclistic, Lily Moreno, believes that the company’s future growth depends on maximizing the number of annual memberships. Hence, the marketing analyst team wants to understand how casual riders and annual members use Cyclistic bikes differently. From these insights, the analytics team could be able to design a new marketing strategy to convert casual riders into annual members. 

Three questions will guide the future marketing campaign:

1.How do annual members and casual riders use Cyclistic bikes differently?

2.Why would casual riders buy Cyclistic annual memberships?

3.How can Cyclistic use digital media to influence casual riders to become members?

I have been assigned by Moreno the first question. 


### The Ask phase

* A statement of the business task: 

Cyclistic has concluded that annual members are much more profitable than casual riders. So, we want to design a marketing strategies and a campaign that helps us converting casual riders into annual members. 

* My key stakeholders are: 

1-Lily Moreno: The director of marketing and my manager. Moreno has initiated   this  strategy. The first stakeholder to deliver to. 

2-The executive team: For Moreno´s idea to work, the executive team must approve our recommendations, so so they must be backed up with compelling data insights and professional data visualizations.


### The Prepare phase

Data Source: 
Past 12 month of original bike share data set from 01/01/2021 to 31/12/2021 was extracted as 12 zipped .csv [files](https://divvy-tripdata.s3.amazonaws.com/index.html). The data is made available and licensed by Motivate International Inc under this [license](https://ride.divvybikes.com/data-license-agreement).

Data Organization & Description:

File naming convention: YYYY_MM

File Type:  csv  format 

File Content: Each csv file consist of 13 columns which contain information related to ride id, rider type, ride start and end time, start and end location  etc. Number of rows varies between 49k to 531k from different excel files.


Data credibility: 

The data set is reliable, the data is complete and accurate for the chosen time window.

The data is original, it is a first arty information.

The data is comprehensive, the data set contains all information needed to answer the question.

The data is current, rider data of the last 12 months was used.

The data is cited and vetted by Chicago department of transportation.


Data Security: Riders’ personal identifiable information is hidden through tokenization.

Original files are backed up in a separate folder.


Data Limitations: As riders’ personal identifiable information is hidden, thus will not be able to connect pass purchases to credit cards numbers to determine if casual riders live in the Cyclistic service area or if they have purchased multiple single passes.

### The Process Phase

I used R for data verification and cleaning: Reasons:
The 12 data sets combined will contain more than 5 million rows of data. Excel worksheet limitation is 1,048,576 rows. Moreover, some csv files could not uploaded to BigQuery for file size problems. Thus, R is used to perform all tasks from organizing, cleaning analyzing and visualizing data.


### The Analyze Phase
#### Setting up the environment

```{r}
# installing packages
install.packages('tidyverse')
install.packages('ggplot2')
install.packages('lubridate')
install.packages('dplyr')
install.packages('readr')
install.packages('janitor')
install.packages('data.table')
install.packages('tidyr')

# Loading the libraries
library(tidyverse)
library(ggplot2)
library(lubridate)
library(dplyr)
library(readr)
library(janitor)
library(data.table)
library(tidyr)

# Load dataset
data <- read_csv("202004-divvy-tripdata.csv")

# Check column names of each dataset for consistency
colnames(data)

# Remove column are not required beyond the scope of project

data <- data %>%
  select(-c(start_lat:end_lng))
glimpse(data)

# Rename columns for better readability

data <- data %>%
  rename(ride_type = rideable_type,
         start_time = started_at,
          end_time = ended_at,
         customer_type = member_casual)
glimpse(data)

# Adding column for day of the week the trip started

data$day_of_the_week <- format(as.Date(data$start_time),'%a')

# Adding column for the month the trip started

data$month <- format(as.Date(data$start_time),'%b_%y')

#column for time of the day when the trip started
#Time element needs to be extracted from start_time. However, as the times must be in POSIXct
#(only times of class POSIXct are supported in ggplot2), a two-step conversion is needed. 
#First the time is converted to a character vector, effectively stripping all the date information. 
#The time is then converted back to POSIXct with today’s date – the date is of no interest to us,

data$time <- format(data$start_time, format = "%H:%M")
data$time <- as.POSIXct(data$time, format = "%H:%M")

#column for trip duration in min
data$trip_duration <- (as.double(difftime(data$end_time, data$start_time)))/60

# check the dataframe
glimpse(data)

# checking for trip lengths less than 0
nrow(subset(data,trip_duration < 0))

#checking for testrides that were made by company for quality checks
nrow(subset(data, start_station_name %like% "TEST"))
nrow(subset(data, start_station_name %like% "test"))
nrow(subset(data, start_station_name %like% "Test"))

# remove negative trip durations 
data2 <- data[!(data$trip_duration < 0),]

#remove test rides
data2<- data2[!((data2$start_station_name %like% "TEST" | data2$start_station_name %like% "test")),]

#check dataframe
glimpse(data2)

# checking count of distinct values
table(data2$customer_type)
#aggregating total trip duration by customer type
setNames(aggregate(trip_duration ~ customer_type, data2, sum), c("customer_type", "total_trip_duration(mins)"))

# statictical summary of trip_duration for all trips
summary(data2$trip_duration)


#statistical summary of trip_duration by customer_type
data2 %>%
  group_by(customer_type) %>%
  summarise(min_trip_duration = min(trip_duration),max_trip_duration = max(trip_duration),
            median_trip_duration = median(trip_duration), mean_trip_duration = mean(trip_duration))

data2 %>% 
  group_by(customer_type, day_of_the_week) %>%  
  summarise(number_of_rides = n(),average_duration_mins = mean(trip_duration)) %>% 
  arrange(customer_type, desc(number_of_rides))

# VISUALISATION

data2 %>%
  group_by(customer_type, day_of_the_week)%>%
  summarise(number_of_rides=n())%>%
  arrange(customer_type,day_of_the_week)%>%
  ggplot(aes(x=day_of_the_week, y=number_of_rides,fill=customer_type))+
  labs(title="total trips by customer types vs day of the week")+
  geom_col(width=0.5,position = position_dodge(width=0.5))

# Average no of trips by customer type and month

data2 %>%
  group_by(customer_type,month)%>%
  summarise(number_of_rides = n(), 'average_duration_(mins)' = mean(trip_duration))%>%
  arrange(customer_type,desc(number_of_rides))

# VISUALISATION

data2 %>%
  group_by(customer_type,month)%>%
  summarise(number_of_rides = n())%>%
  arrange(customer_type,month)%>%
  ggplot(aes(x=month, y = number_of_rides, fill = customer_type))+
  labs(title = "total trips by customer type Vs. month")+
  theme(axis.text.x = element_text(angle=30))+
  geom_col(width=0.5, position = position_dodge(width=0.5))

# Visualisation of average trip duration by custome type on each day of the week

data2 %>%  
  group_by(customer_type, day_of_the_week) %>% 
  summarise(average_trip_duration = mean(trip_duration)) %>%
  ggplot(aes(x = day_of_the_week, y = average_trip_duration, fill = customer_type)) +
  geom_col(width=0.5, position = position_dodge(width=0.5)) + 
  labs(title ="Average trip duration by customer type Vs. Day of the week")

# Visualizaton of bike demand over 24 hr period (a day)

data2 %>%  
  group_by(customer_type, time) %>% 
  summarise(number_of_trips = n()) %>%
  ggplot(aes(x = time, y = number_of_trips, color = customer_type, group = customer_type)) +
  geom_line() +
  scale_x_datetime(date_breaks = "1 hour", minor_breaks = NULL,
                   date_labels = "%H:%M", expand = c(0,0)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title ="Demand over 24 hours of a day", x = "Time of the day")


data2 %>%
  group_by(ride_type, customer_type) %>%
  summarise(number_of_trips = n()) %>%  
  ggplot(aes(x= ride_type, y=number_of_trips, fill= customer_type))+
  geom_bar(width = 0.2, stat='identity') +
  labs(title ="Ride type Vs. Number of trips")
```


#### Conclusions/Summary of insights 

Members and casual riders differ in how long they use the bikes, how often they use the bikes, and on which days of the week does every group peak:

* Casual rides peak during weekends (plot3). There is a high probability they are tourists visiting and sightseeing the city, or that they are ordinary Chicago residents who are riding bike in their leisure time during the weekend. The longer average ride time for casual rider (plot2), also peaking at the weekend,  provides evidence for this point.

* Ride length for members are relatively shorter compared to casual riders. This could clarified as such, that most members use the bikes to commute on workdays. This clarification would also explain the short riding durations of members. They ride from point A to B, namely roughly always the same ride lengths and the same distance

* Ridership start to pick up (plot8) from February (from Spring through Summer)and start to decrease in August (from Fall through winter). This correlation is due to the seasonal changes. As the weather start to get warmer and more pleasant in February (start of Spring), more people starts to cycle, and inversely when the weather  becomes less warm cold around September (start of Fall).

* More than 50% of the riders are annual members (plot5), suggesting that the company have already achieved a certain level of loyalty among its bike users. This indicates a positive message, namely that the company is going to be able to convince many casual riders to convert to members, and to keep the new members satisfied. 


#### Recommendations

Give discounts for longer rides when you have a membership
Longer rides can get some type of rewards program when they become members

* The marketing campaign should be launched between February to August, as the number of trips made by casual riders peaks at this time of the year.

* As casual rider usage reach its highest point on the weekend, the marketing campaign can include weekend-only membership at a sensible price. This could attract casual riders to convert to members.

* The campaign could include ride-length-based tariff plan (maybe only on weekends): Bike more, pay less ! 
This provides more incentive for the member rides to cycle longer distances. 

* Alternatively, longer rides can be rewarded with benefits such as discount vouchers. 

